{
  "nav": {
    "home": "Home",
    "forOwners": "For Owners",
    "forVets": "For Veterinarians",
    "hub": "Hub",
    "findVet": "Find a Vet",
    "login": "Log In",
    "register": "Get Started",
    "dashboard": "Dashboard",
    "pets": "My Pets",
    "messages": "Messages",
    "appointments": "Appointments",
    "notifications": "Notifications",
    "account": "Account",
    "logout": "Log Out",
    "vetDashboard": "Vet Dashboard",
    "admin": "Admin"
  },
  "auth": {
    "loginTitle": "Welcome back",
    "loginSubtitle": "Sign in to your ZOARIA account",
    "registerTitle": "Join ZOARIA",
    "registerSubtitle": "Create your account in seconds",
    "email": "Email address",
    "password": "Password",
    "confirmPassword": "Confirm password",
    "name": "Full name",
    "forgotPassword": "Forgot password?",
    "rememberMe": "Remember me",
    "loginBtn": "Sign In",
    "registerBtn": "Create Account",
    "noAccount": "Don't have an account?",
    "hasAccount": "Already have an account?",
    "asOwner": "Pet Owner",
    "asVet": "Veterinarian",
    "verifyEmailTitle": "Check your inbox",
    "verifyEmailText": "We sent a verification link to",
    "forgotTitle": "Reset your password",
    "forgotText": "Enter your email and we'll send you a reset link.",
    "sendResetLink": "Send Reset Link",
    "resetTitle": "Set new password",
    "resetBtn": "Reset Password"
  },
  "dashboard": {
    "greeting": "Good",
    "morning": "morning",
    "afternoon": "afternoon",
    "evening": "evening",
    "yourPets": "Your Pets",
    "noActivity": "No recent activity",
    "upcomingReminders": "Upcoming Reminders",
    "recentActivity": "Recent Activity",
    "quickActions": "Quick Actions",
    "addPet": "Add Pet",
    "bookAppointment": "Book Appointment",
    "findVet": "Find a Vet",
    "viewRecords": "View Records"
  },
  "pets": {
    "title": "My Pets",
    "addNew": "Add Pet",
    "noPets": "No pets yet",
    "noPetsText": "Add your first pet to get started",
    "name": "Pet Name",
    "species": "Species",
    "breed": "Breed",
    "gender": "Gender",
    "age": "Age (months)",
    "weight": "Weight (kg)",
    "idealWeight": "Ideal Weight (kg)",
    "height": "Height (cm)",
    "sterilized": "Sterilized",
    "activityLevel": "Activity Level",
    "chipNumber": "Chip Number",
    "medicalNotes": "Medical Notes",
    "selectSpecies": "Select species",
    "selectBreed": "Select breed",
    "male": "Male",
    "female": "Female",
    "unknown": "Unknown",
    "low": "Low",
    "moderate": "Moderate",
    "active": "Active",
    "veryActive": "Very Active",
    "healthy": "Healthy Weight",
    "overweight": "Overweight",
    "underweight": "Underweight",
    "bmi": "Weight Status",
    "rer": "RER",
    "mer": "Daily Calories (MER)",
    "conditions": "Breed Health Risks",
    "feeding": "Feeding",
    "activity": "Activity",
    "health": "Health Records",
    "calendar": "Calendar",
    "vitaminCWarning": "\u26a0\ufe0f Guinea pigs cannot synthesize Vitamin C. Ensure daily supplementation through vegetables (bell peppers, broccoli) or supplements."
  },
  "plans": {
    "basic": "Basic",
    "standard": "Standard",
    "premium": "Premium",
    "free": "Free",
    "perMonth": "/month",
    "upgrade": "Upgrade",
    "current": "Current Plan",
    "petsLimit": "Up to {n} pet(s)",
    "unlimitedPets": "Unlimited pets"
  },
  "common": {
    "save": "Save",
    "cancel": "Cancel",
    "delete": "Delete",
    "edit": "Edit",
    "loading": "Loading...",
    "error": "Something went wrong",
    "success": "Success",
    "search": "Search",
    "noResults": "No results found",
    "viewAll": "View All",
    "back": "Back",
    "next": "Next",
    "submit": "Submit",
    "confirm": "Confirm",
    "close": "Close",
    "optional": "Optional",
    "required": "Required"
  }
}