{
  "name": "zoaria-frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.2.35",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "next-intl": "^3.17.2",
    "zustand": "^4.5.4",
    "axios": "^1.7.3",
    "@tanstack/react-query": "^5.51.1",
    "react-hook-form": "^7.52.2",
    "zod": "^3.23.8",
    "@hookform/resolvers": "^3.9.0",
    "date-fns": "^3.6.0",
    "react-calendar": "^5.0.0",
    "recharts": "^2.12.7",
    "lucide-react": "^0.414.0",
    "clsx": "^2.1.1",
    "tailwind-merge": "^2.4.0",
    "framer-motion": "^11.3.19",
    "@radix-ui/react-dialog": "^1.1.1",
    "@radix-ui/react-dropdown-menu": "^2.1.1",
    "@radix-ui/react-select": "^2.1.1",
    "@radix-ui/react-tabs": "^1.1.0",
    "@radix-ui/react-tooltip": "^1.1.2",
    "@radix-ui/react-avatar": "^1.1.0",
    "@radix-ui/react-switch": "^1.1.0",
    "@radix-ui/react-progress": "^1.1.0",
    "@radix-ui/react-toast": "^1.2.1",
    "js-cookie": "^3.0.5",
    "react-dropzone": "^14.2.3"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@types/js-cookie": "^3.0.6",
    "tailwindcss": "^3.4.6",
    "autoprefixer": "^10.4.19",
    "postcss": "^8.4.40",
    "eslint": "^8",
    "eslint-config-next": "14.2.35"
  }
}
